---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: docker.io-envoyproxy-gateway-helm
  namespace: ${workspaceNamespace}
spec:
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.3.2
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: docker.io-envoyproxy-gateway-helm
    namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: envoy
  targetNamespace: envoy-gateway-system