---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: docker.io-envoyproxy-gateway-helm
  namespace: ${workspaceNamespace}
spec:
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.3.2
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: docker.io-envoyproxy-gateway-helm
    namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: envoy
  targetNamespace: envoy-gateway-system
  values:
    deployment:
      envoyGateway:
        image:
          repository: registry.wskn.local/library/envoyproxy/gateway
          tag: v1.3.2
    config:
      envoyGateway:
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        logging:
          level:
            default: info
        provider:
          type: Kubernetes
          kubernetes:
            envoyDeployment:
              container:
                image: registry.wskn.local/library/envoyproxy/envoy:distroless-v1.33.1
            rateLimitDeployment:
              container:
                image: registry.wskn.local/library/envoyproxy/ratelimit:0141a24f
            shutdownManager:
              image: registry.wskn.local/library/envoyproxy/gateway:v1.3.2