apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgvector
  namespace: ${workspaceNamespace}
spec:
  instances: 1
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pgvector-app
  namespace: ${workspaceNamespace}
spec:
  name: app
  owner: app
  cluster:
    name: pgvector
  extensions:
  - name: vector

